language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - sunspot/vendor/bundle
    - sunspot_solr/vendor/bundle
    - sunspot_rails/vendor/bundle

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.3.1
  - 2.4.3
  - 2.5.0
  # - rbx-2.0
  # - jruby

env:
  - GEM=sunspot
  - GEM=sunspot_rails
  - GEM=sunspot_solr

script:
  - ci/travis.sh

